name: Test Coverage

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm
  COVERAGE: PartialSummary

jobs:
  test:
    name: Agentic Runner
    runs-on: [self-hosted, agentic]
    
    steps:
    - name: Install dependencies
      run: |
        bundle config set path "$(ruby -e 'puts Gem.user_dir')"
        bundle install
    
    - name: Run tests
      timeout-minutes: 60
      run: bundle exec bake test

    - uses: actions/upload-artifact@v3
      with:
        name: coverage-agentic-runner
        path: .covered.db
  
  validate:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true
    
    - uses: actions/download-artifact@v3
    
    - name: Validate coverage
      timeout-minutes: 5
      run: bundle exec bake covered:validate --paths */.covered.db \;
