name: Test Agent Context

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: XTerm

jobs:
  test:
    name: Agent Context
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    services:
      ollama:
        image: ollama/ollama
        ports:
          - 11434:11434
        
    
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - "3.4"
        
        experimental: [false]
        
        include:
          - os: ubuntu
            ruby: head
            experimental: true
    
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Wait for Ollama to be ready
      run: |
        for i in {1..30}; do
          curl -s http://localhost:11434/api/tags && break
          sleep 2
        done

    - name: Pull Model
      run: |
        curl -X POST http://localhost:11434/api/pull -d '{"name": "llama3.1"}'
    
    - name: Run tests
      timeout-minutes: 30
      run: bundle exec bake test
